# Welcome to Jekyll!
# port: 8800

# Site settings
title: Plus62 Store
description: > # this means to ignore newlines until "baseurl:"
  Toko Online AI commerce - Plus62 Store
logo: https://plus62store.github.io/assets/images/logo/plus62.webp
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

collections:
  products:
    output: true
    permalink: /product/:path/
    
# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - dotenv

plugins_dir: _plugins
